server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name it-krug.de www.it-krug.de;

    root /var/www/it-krug.de;
    index index.html;

    gzip on;
    gzip_types text/css text/javascript application/javascript;
    gzip_min_length 1024;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|jpg|png|svg|ico|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
}
